from colorama import Fore, Back, Style

"""
Contains all configuration constants
"""

REQ_HEIGHT = 30
REQ_WIDTH = 125
FRAME_TIME = 0.1

UNTOUCHED_MINBOUND = 0.80
MODERATE_DMG_MINBOUND = 0.35
CRITICAL_DMG_MINBOUND = 0.0
MODERATE_DMG_COLOR = Fore.YELLOW
CRITICAL_DMG_COLOR = Fore.RED
DAMAGE_TICK_COLOR = Fore.LIGHTRED_EX

BG_COLOR = Back.LIGHTGREEN_EX
KING_COLOR = Fore.BLACK
WALL_COLOR = Fore.WHITE
HUT_COLOR = Fore.BLACK
CANNON_COLOR = Fore.BLACK
BARBARIAN_COLOR = Fore.BLUE
SPAWNPOINT_COLOR = Fore.MAGENTA
ASCII_LOSE_COLOR = Fore.RED
ASCII_WIN_COLOR = Fore.GREEN

CANNON_FDELAY = 10
BARBARIAN_FDELAY = 10

REPLAY_DIR = "replays/"