from colorama import Fore, Back, Style

"""
Contains all configuration constants
"""

REQ_HEIGHT = 30
REQ_WIDTH = 125
FRAME_TIME = 0.1

UNTOUCHED_MINBOUND = 0.80
MODERATE_DMG_MINBOUND = 0.35
CRITICAL_DMG_MINBOUND = 0.0
UNTOUCHED_COLOR = Fore.WHITE
MODERATE_DMG_COLOR = Fore.YELLOW
CRITICAL_DMG_COLOR = Fore.RED

BG_COLOR = Back.LIGHTGREEN_EX
KING_COLOR = Fore.RED
WALL_COLOR = Fore.WHITE
HUT_COLOR = Fore.WHITE