from colorama import Fore, Back, Style

"""
Contains all configuration constants
"""

REQ_HEIGHT = 30
REQ_WIDTH = 125
FRAME_TIME = 0.1

UNTOUCHED_MINBOUND = 0.80
MODERATE_DMG_MINBOUND = 0.35
CRITICAL_DMG_MINBOUND = 0.0
MODERATE_DMG_COLOR = Fore.YELLOW
CRITICAL_DMG_COLOR = Fore.RED
DAMAGE_TICK_COLOR = Fore.LIGHTRED_EX

BG_COLOR = Back.LIGHTGREEN_EX
KING_COLOR = Fore.BLACK
WALL_COLOR = Fore.WHITE
HUT_COLOR = Fore.BLACK
CANNON_COLOR = Fore.BLACK
BARBARIAN_COLOR = Fore.BLUE
BALLOON_COLOR = Fore.LIGHTBLUE_EX
ARCHER_COLOR = Fore.YELLOW
SPAWNPOINT_COLOR = Fore.MAGENTA
ASCII_LOSE_COLOR = Fore.RED
ASCII_WIN_COLOR = Fore.GREEN

CANNON_FDELAY = 10

KING_SPEED = 1

BARBARIAN_ATK = 4
BARBARIAN_HEALTH = 30
BARBARIAN_SPEED = 1
BARBARIAN_RANGE = 1
BARBARIAN_FDELAY = 10

ARCHER_ATK = 2
ARCHER_HEALTH = 15
ARCHER_SPEED = 2
ARCHER_RANGE = 7
ARCHER_FDELAY = 10

BALLOON_ATK = 8
BALLOON_HEALTH = 30
BALLOON_SPEED = 2
BALLOON_RANGE = 2
BALLOON_FDELAY = 10

REPLAY_DIR = "replays/"